/**
 * Autogenerated by Thrift Compiler (0.17.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace HiveClient.Sql.ThriftApi.TCLService.TTypes
{

  public partial class THandleIdentifier : TBase
  {
    private byte[]? _guid;
    private byte[]? _secret;

    public byte[]? Guid
    {
      get
      {
        return _guid;
      }
      set
      {
        __isset.guid = true;
        this._guid = value;
      }
    }

    public byte[]? Secret
    {
      get
      {
        return _secret;
      }
      set
      {
        __isset.secret = true;
        this._secret = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool guid;
      public bool secret;
    }

    public THandleIdentifier()
    {
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String)
              {
                Guid = await iprot.ReadBinaryAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.String)
              {
                Secret = await iprot.ReadBinaryAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp245 = new TStruct("THandleIdentifier");
        await oprot.WriteStructBeginAsync(tmp245, cancellationToken);
        var tmp246 = new TField();
        if((Guid != null) && __isset.guid)
        {
          tmp246.Name = "guid";
          tmp246.Type = TType.String;
          tmp246.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp246, cancellationToken);
          await oprot.WriteBinaryAsync(Guid, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Secret != null) && __isset.secret)
        {
          tmp246.Name = "secret";
          tmp246.Type = TType.String;
          tmp246.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp246, cancellationToken);
          await oprot.WriteBinaryAsync(Secret, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object? that)
    {
      if (that is not THandleIdentifier other) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.guid == other.__isset.guid) && ((!__isset.guid) || (TCollections.Equals(Guid, other.Guid))))
        && ((__isset.secret == other.__isset.secret) && ((!__isset.secret) || (TCollections.Equals(Secret, other.Secret))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Guid != null) && __isset.guid)
        {
          hashcode = (hashcode * 397) + Guid.GetHashCode();
        }
        if((Secret != null) && __isset.secret)
        {
          hashcode = (hashcode * 397) + Secret.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp247 = new StringBuilder("THandleIdentifier(");
      int tmp248 = 0;
      if((Guid != null) && __isset.guid)
      {
        if(0 < tmp248++) { tmp247.Append(", "); }
        tmp247.Append("Guid: ");
        Guid.ToString(tmp247);
      }
      if((Secret != null) && __isset.secret)
      {
        if(0 < tmp248++) { tmp247.Append(", "); }
        tmp247.Append("Secret: ");
        Secret.ToString(tmp247);
      }
      tmp247.Append(')');
      return tmp247.ToString();
    }
  }

}
