/**
 * Autogenerated by Thrift Compiler (0.17.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace HiveClient.Sql.ThriftApi.TCLService.TTypes
{

  public partial class TSparkArrowTypes : TBase
  {
    private bool _timestampAsArrow;
    private bool _decimalAsArrow;
    private bool _complexTypesAsArrow;
    private bool _intervalTypesAsArrow;

    public bool TimestampAsArrow
    {
      get
      {
        return _timestampAsArrow;
      }
      set
      {
        __isset.timestampAsArrow = true;
        this._timestampAsArrow = value;
      }
    }

    public bool DecimalAsArrow
    {
      get
      {
        return _decimalAsArrow;
      }
      set
      {
        __isset.decimalAsArrow = true;
        this._decimalAsArrow = value;
      }
    }

    public bool ComplexTypesAsArrow
    {
      get
      {
        return _complexTypesAsArrow;
      }
      set
      {
        __isset.complexTypesAsArrow = true;
        this._complexTypesAsArrow = value;
      }
    }

    public bool IntervalTypesAsArrow
    {
      get
      {
        return _intervalTypesAsArrow;
      }
      set
      {
        __isset.intervalTypesAsArrow = true;
        this._intervalTypesAsArrow = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool timestampAsArrow;
      public bool decimalAsArrow;
      public bool complexTypesAsArrow;
      public bool intervalTypesAsArrow;
    }

    public TSparkArrowTypes()
    {
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Bool)
              {
                TimestampAsArrow = await iprot.ReadBoolAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.Bool)
              {
                DecimalAsArrow = await iprot.ReadBoolAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.Bool)
              {
                ComplexTypesAsArrow = await iprot.ReadBoolAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 4:
              if (field.Type == TType.Bool)
              {
                IntervalTypesAsArrow = await iprot.ReadBoolAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp316 = new TStruct("TSparkArrowTypes");
        await oprot.WriteStructBeginAsync(tmp316, cancellationToken);
        var tmp317 = new TField();
        if(__isset.timestampAsArrow)
        {
          tmp317.Name = "timestampAsArrow";
          tmp317.Type = TType.Bool;
          tmp317.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp317, cancellationToken);
          await oprot.WriteBoolAsync(TimestampAsArrow, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.decimalAsArrow)
        {
          tmp317.Name = "decimalAsArrow";
          tmp317.Type = TType.Bool;
          tmp317.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp317, cancellationToken);
          await oprot.WriteBoolAsync(DecimalAsArrow, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.complexTypesAsArrow)
        {
          tmp317.Name = "complexTypesAsArrow";
          tmp317.Type = TType.Bool;
          tmp317.ID = 3;
          await oprot.WriteFieldBeginAsync(tmp317, cancellationToken);
          await oprot.WriteBoolAsync(ComplexTypesAsArrow, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.intervalTypesAsArrow)
        {
          tmp317.Name = "intervalTypesAsArrow";
          tmp317.Type = TType.Bool;
          tmp317.ID = 4;
          await oprot.WriteFieldBeginAsync(tmp317, cancellationToken);
          await oprot.WriteBoolAsync(IntervalTypesAsArrow, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object? that)
    {
      if (that is not TSparkArrowTypes other) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.timestampAsArrow == other.__isset.timestampAsArrow) && ((!__isset.timestampAsArrow) || (global::System.Object.Equals(TimestampAsArrow, other.TimestampAsArrow))))
        && ((__isset.decimalAsArrow == other.__isset.decimalAsArrow) && ((!__isset.decimalAsArrow) || (global::System.Object.Equals(DecimalAsArrow, other.DecimalAsArrow))))
        && ((__isset.complexTypesAsArrow == other.__isset.complexTypesAsArrow) && ((!__isset.complexTypesAsArrow) || (global::System.Object.Equals(ComplexTypesAsArrow, other.ComplexTypesAsArrow))))
        && ((__isset.intervalTypesAsArrow == other.__isset.intervalTypesAsArrow) && ((!__isset.intervalTypesAsArrow) || (global::System.Object.Equals(IntervalTypesAsArrow, other.IntervalTypesAsArrow))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if(__isset.timestampAsArrow)
        {
          hashcode = (hashcode * 397) + TimestampAsArrow.GetHashCode();
        }
        if(__isset.decimalAsArrow)
        {
          hashcode = (hashcode * 397) + DecimalAsArrow.GetHashCode();
        }
        if(__isset.complexTypesAsArrow)
        {
          hashcode = (hashcode * 397) + ComplexTypesAsArrow.GetHashCode();
        }
        if(__isset.intervalTypesAsArrow)
        {
          hashcode = (hashcode * 397) + IntervalTypesAsArrow.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp318 = new StringBuilder("TSparkArrowTypes(");
      int tmp319 = 0;
      if(__isset.timestampAsArrow)
      {
        if(0 < tmp319++) { tmp318.Append(", "); }
        tmp318.Append("TimestampAsArrow: ");
        TimestampAsArrow.ToString(tmp318);
      }
      if(__isset.decimalAsArrow)
      {
        if(0 < tmp319++) { tmp318.Append(", "); }
        tmp318.Append("DecimalAsArrow: ");
        DecimalAsArrow.ToString(tmp318);
      }
      if(__isset.complexTypesAsArrow)
      {
        if(0 < tmp319++) { tmp318.Append(", "); }
        tmp318.Append("ComplexTypesAsArrow: ");
        ComplexTypesAsArrow.ToString(tmp318);
      }
      if(__isset.intervalTypesAsArrow)
      {
        if(0 < tmp319++) { tmp318.Append(", "); }
        tmp318.Append("IntervalTypesAsArrow: ");
        IntervalTypesAsArrow.ToString(tmp318);
      }
      tmp318.Append(')');
      return tmp318.ToString();
    }
  }

}
