/**
 * Autogenerated by Thrift Compiler (0.17.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace HiveClient.Sql.ThriftApi.TCLService.TTypes
{

  public partial class TStringColumn : TBase
  {
    private List<string>? _values;
    private byte[]? _nulls;

    public List<string>? Values
    {
      get
      {
        return _values;
      }
      set
      {
        __isset.values = true;
        this._values = value;
      }
    }

    public byte[]? Nulls
    {
      get
      {
        return _nulls;
      }
      set
      {
        __isset.nulls = true;
        this._nulls = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool values;
      public bool nulls;
    }

    public TStringColumn()
    {
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List)
              {
                {
                  var _list159 = await iprot.ReadListBeginAsync(cancellationToken);
                  Values = new List<string>(_list159.Count);
                  for(int _i160 = 0; _i160 < _list159.Count; ++_i160)
                  {
                    string _elem161;
                    _elem161 = await iprot.ReadStringAsync(cancellationToken);
                    Values.Add(_elem161);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.String)
              {
                Nulls = await iprot.ReadBinaryAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp162 = new TStruct("TStringColumn");
        await oprot.WriteStructBeginAsync(tmp162, cancellationToken);
        var tmp163 = new TField();
        if((Values != null) && __isset.values)
        {
          tmp163.Name = "values";
          tmp163.Type = TType.List;
          tmp163.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp163, cancellationToken);
          await oprot.WriteListBeginAsync(new TList(TType.String, Values.Count), cancellationToken);
          foreach (string _iter164 in Values)
          {
            await oprot.WriteStringAsync(_iter164, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Nulls != null) && __isset.nulls)
        {
          tmp163.Name = "nulls";
          tmp163.Type = TType.String;
          tmp163.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp163, cancellationToken);
          await oprot.WriteBinaryAsync(Nulls, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object? that)
    {
      if (that is not TStringColumn other) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.values == other.__isset.values) && ((!__isset.values) || (TCollections.Equals(Values, other.Values))))
        && ((__isset.nulls == other.__isset.nulls) && ((!__isset.nulls) || (TCollections.Equals(Nulls, other.Nulls))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Values != null) && __isset.values)
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Values);
        }
        if((Nulls != null) && __isset.nulls)
        {
          hashcode = (hashcode * 397) + Nulls.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp165 = new StringBuilder("TStringColumn(");
      int tmp166 = 0;
      if((Values != null) && __isset.values)
      {
        if(0 < tmp166++) { tmp165.Append(", "); }
        tmp165.Append("Values: ");
        Values.ToString(tmp165);
      }
      if((Nulls != null) && __isset.nulls)
      {
        if(0 < tmp166++) { tmp165.Append(", "); }
        tmp165.Append("Nulls: ");
        Nulls.ToString(tmp165);
      }
      tmp165.Append(')');
      return tmp165.ToString();
    }
  }

}
