/**
 * Autogenerated by Thrift Compiler (0.17.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;


#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace DataBricks.Sql.ThriftApi.TCLService.TTypes
{
  public static class dbxsqlExtensions
  {
    public static bool Equals(this Dictionary<string, global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TTypeQualifierValue> instance, object that)
    {
      if (that is not Dictionary<string, global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TTypeQualifierValue> other) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this Dictionary<string, global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TTypeQualifierValue> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this Dictionary<string, int> instance, object that)
    {
      if (that is not Dictionary<string, int> other) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this Dictionary<string, int> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this Dictionary<string, string> instance, object that)
    {
      if (that is not Dictionary<string, string> other) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this Dictionary<string, string> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<bool> instance, object that)
    {
      if (that is not List<bool> other) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<bool> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<byte[]> instance, object that)
    {
      if (that is not List<byte[]> other) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<byte[]> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<double> instance, object that)
    {
      if (that is not List<double> other) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<double> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TColumn> instance, object that)
    {
      if (that is not List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TColumn> other) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TColumn> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TColumnDesc> instance, object that)
    {
      if (that is not List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TColumnDesc> other) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TColumnDesc> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TColumnValue> instance, object that)
    {
      if (that is not List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TColumnValue> other) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TColumnValue> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TDBSqlTempView> instance, object that)
    {
      if (that is not List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TDBSqlTempView> other) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TDBSqlTempView> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TGetInfoValue> instance, object that)
    {
      if (that is not List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TGetInfoValue> other) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TGetInfoValue> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TRow> instance, object that)
    {
      if (that is not List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TRow> other) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TRow> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TSparkArrowBatch> instance, object that)
    {
      if (that is not List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TSparkArrowBatch> other) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TSparkArrowBatch> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TSparkArrowResultLink> instance, object that)
    {
      if (that is not List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TSparkArrowResultLink> other) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TSparkArrowResultLink> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TTypeEntry> instance, object that)
    {
      if (that is not List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TTypeEntry> other) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TTypeEntry> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<int> instance, object that)
    {
      if (that is not List<int> other) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<int> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<long> instance, object that)
    {
      if (that is not List<long> other) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<long> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<sbyte> instance, object that)
    {
      if (that is not List<sbyte> other) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<sbyte> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<short> instance, object that)
    {
      if (that is not List<short> other) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<short> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<string> instance, object that)
    {
      if (that is not List<string> other) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<string> instance)
    {
      return TCollections.GetHashCode(instance);
    }


  }
}
