/**
 * Autogenerated by Thrift Compiler (0.17.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace DataBricks.Sql.ThriftApi.TCLService.TTypes
{

  public partial class GetOperationStatus_args : TBase
  {
    private global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TGetOperationStatusReq? _req;

    public global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TGetOperationStatusReq? Req
    {
      get
      {
        return _req;
      }
      set
      {
        __isset.req = true;
        this._req = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool req;
    }

    public GetOperationStatus_args()
    {
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct)
              {
                Req = new global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TGetOperationStatusReq();
                await Req.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp489 = new TStruct("GetOperationStatus_args");
        await oprot.WriteStructBeginAsync(tmp489, cancellationToken);
        var tmp490 = new TField();
        if((Req != null) && __isset.req)
        {
          tmp490.Name = "req";
          tmp490.Type = TType.Struct;
          tmp490.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp490, cancellationToken);
          await Req.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object? that)
    {
      if (that is not GetOperationStatus_args other) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.req == other.__isset.req) && ((!__isset.req) || (global::System.Object.Equals(Req, other.Req))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Req != null) && __isset.req)
        {
          hashcode = (hashcode * 397) + Req.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp491 = new StringBuilder("GetOperationStatus_args(");
      int tmp492 = 0;
      if((Req != null) && __isset.req)
      {
        if(0 < tmp492++) { tmp491.Append(", "); }
        tmp491.Append("Req: ");
        Req.ToString(tmp491);
      }
      tmp491.Append(')');
      return tmp491.ToString();
    }
  }

}
