/**
 * Autogenerated by Thrift Compiler (0.17.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace DataBricks.Sql.ThriftApi.TCLService.TTypes
{

  public partial class TGetTablesResp : TBase
  {
    private global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TStatus? _status;
    private global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TOperationHandle? _operationHandle;
    private global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TSparkDirectResults? _directResults;

    public global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TStatus? Status
    {
      get
      {
        return _status;
      }
      set
      {
        __isset.status = true;
        this._status = value;
      }
    }

    public global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TOperationHandle? OperationHandle
    {
      get
      {
        return _operationHandle;
      }
      set
      {
        __isset.operationHandle = true;
        this._operationHandle = value;
      }
    }

    public global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TSparkDirectResults? DirectResults
    {
      get
      {
        return _directResults;
      }
      set
      {
        __isset.directResults = true;
        this._directResults = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool status;
      public bool operationHandle;
      public bool directResults;
    }

    public TGetTablesResp()
    {
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct)
              {
                Status = new global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TStatus();
                await Status.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.Struct)
              {
                OperationHandle = new global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TOperationHandle();
                await OperationHandle.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 1281:
              if (field.Type == TType.Struct)
              {
                DirectResults = new global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TSparkDirectResults();
                await DirectResults.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp485 = new TStruct("TGetTablesResp");
        await oprot.WriteStructBeginAsync(tmp485, cancellationToken);
        var tmp486 = new TField();
        if((Status != null) && __isset.status)
        {
          tmp486.Name = "status";
          tmp486.Type = TType.Struct;
          tmp486.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp486, cancellationToken);
          await Status.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((OperationHandle != null) && __isset.operationHandle)
        {
          tmp486.Name = "operationHandle";
          tmp486.Type = TType.Struct;
          tmp486.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp486, cancellationToken);
          await OperationHandle.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((DirectResults != null) && __isset.directResults)
        {
          tmp486.Name = "directResults";
          tmp486.Type = TType.Struct;
          tmp486.ID = 1281;
          await oprot.WriteFieldBeginAsync(tmp486, cancellationToken);
          await DirectResults.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object? that)
    {
      if (that is not TGetTablesResp other) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.status == other.__isset.status) && ((!__isset.status) || (global::System.Object.Equals(Status, other.Status))))
        && ((__isset.operationHandle == other.__isset.operationHandle) && ((!__isset.operationHandle) || (global::System.Object.Equals(OperationHandle, other.OperationHandle))))
        && ((__isset.directResults == other.__isset.directResults) && ((!__isset.directResults) || (global::System.Object.Equals(DirectResults, other.DirectResults))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Status != null) && __isset.status)
        {
          hashcode = (hashcode * 397) + Status.GetHashCode();
        }
        if((OperationHandle != null) && __isset.operationHandle)
        {
          hashcode = (hashcode * 397) + OperationHandle.GetHashCode();
        }
        if((DirectResults != null) && __isset.directResults)
        {
          hashcode = (hashcode * 397) + DirectResults.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp487 = new StringBuilder("TGetTablesResp(");
      int tmp488 = 0;
      if((Status != null) && __isset.status)
      {
        if(0 < tmp488++) { tmp487.Append(", "); }
        tmp487.Append("Status: ");
        Status.ToString(tmp487);
      }
      if((OperationHandle != null) && __isset.operationHandle)
      {
        if(0 < tmp488++) { tmp487.Append(", "); }
        tmp487.Append("OperationHandle: ");
        OperationHandle.ToString(tmp487);
      }
      if((DirectResults != null) && __isset.directResults)
      {
        if(0 < tmp488++) { tmp487.Append(", "); }
        tmp487.Append("DirectResults: ");
        DirectResults.ToString(tmp487);
      }
      tmp487.Append(')');
      return tmp487.ToString();
    }
  }

}
