/**
 * Autogenerated by Thrift Compiler (0.17.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace DataBricks.Sql.ThriftApi.TCLService.TTypes
{

  public partial class TPrimitiveTypeEntry : TBase
  {
    private global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TTypeId _type;
    private global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TTypeQualifiers? _typeQualifiers;

    /// <summary>
    /// 
    /// <seealso cref="global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TTypeId"/>
    /// </summary>
    public global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TTypeId Type
    {
      get
      {
        return _type;
      }
      set
      {
        __isset.type = true;
        this._type = value;
      }
    }

    public global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TTypeQualifiers? TypeQualifiers
    {
      get
      {
        return _typeQualifiers;
      }
      set
      {
        __isset.typeQualifiers = true;
        this._typeQualifiers = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool type;
      public bool typeQualifiers;
    }

    public TPrimitiveTypeEntry()
    {
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32)
              {
                Type = (global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TTypeId)await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.Struct)
              {
                TypeQualifiers = new global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TTypeQualifiers();
                await TypeQualifiers.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp13 = new TStruct("TPrimitiveTypeEntry");
        await oprot.WriteStructBeginAsync(tmp13, cancellationToken);
        var tmp14 = new TField();
        if(__isset.type)
        {
          tmp14.Name = "type";
          tmp14.Type = TType.I32;
          tmp14.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp14, cancellationToken);
          await oprot.WriteI32Async((int)Type, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((TypeQualifiers != null) && __isset.typeQualifiers)
        {
          tmp14.Name = "typeQualifiers";
          tmp14.Type = TType.Struct;
          tmp14.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp14, cancellationToken);
          await TypeQualifiers.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object? that)
    {
      if (that is not TPrimitiveTypeEntry other) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.type == other.__isset.type) && ((!__isset.type) || (global::System.Object.Equals(Type, other.Type))))
        && ((__isset.typeQualifiers == other.__isset.typeQualifiers) && ((!__isset.typeQualifiers) || (global::System.Object.Equals(TypeQualifiers, other.TypeQualifiers))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if(__isset.type)
        {
          hashcode = (hashcode * 397) + Type.GetHashCode();
        }
        if((TypeQualifiers != null) && __isset.typeQualifiers)
        {
          hashcode = (hashcode * 397) + TypeQualifiers.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp15 = new StringBuilder("TPrimitiveTypeEntry(");
      int tmp16 = 0;
      if(__isset.type)
      {
        if(0 < tmp16++) { tmp15.Append(", "); }
        tmp15.Append("Type: ");
        Type.ToString(tmp15);
      }
      if((TypeQualifiers != null) && __isset.typeQualifiers)
      {
        if(0 < tmp16++) { tmp15.Append(", "); }
        tmp15.Append("TypeQualifiers: ");
        TypeQualifiers.ToString(tmp15);
      }
      tmp15.Append(')');
      return tmp15.ToString();
    }
  }

}
