/**
 * Autogenerated by Thrift Compiler (0.17.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#nullable enable                 // requires C# 8.0
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static

namespace DataBricks.Sql.ThriftApi.TCLService.TTypes
{

  public partial class TTypeQualifiers : TBase
  {
    private Dictionary<string, global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TTypeQualifierValue>? _qualifiers;

    public Dictionary<string, global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TTypeQualifierValue>? Qualifiers
    {
      get
      {
        return _qualifiers;
      }
      set
      {
        __isset.qualifiers = true;
        this._qualifiers = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool qualifiers;
    }

    public TTypeQualifiers()
    {
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Map)
              {
                {
                  var _map4 = await iprot.ReadMapBeginAsync(cancellationToken);
                  Qualifiers = new Dictionary<string, global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TTypeQualifierValue>(_map4.Count);
                  for(int _i5 = 0; _i5 < _map4.Count; ++_i5)
                  {
                    string _key6;
                    global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TTypeQualifierValue _val7;
                    _key6 = await iprot.ReadStringAsync(cancellationToken);
                    _val7 = new global::DataBricks.Sql.ThriftApi.TCLService.TTypes.TTypeQualifierValue();
                    await _val7.ReadAsync(iprot, cancellationToken);
                    Qualifiers[_key6] = _val7;
                  }
                  await iprot.ReadMapEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp8 = new TStruct("TTypeQualifiers");
        await oprot.WriteStructBeginAsync(tmp8, cancellationToken);
        var tmp9 = new TField();
        if((Qualifiers != null) && __isset.qualifiers)
        {
          tmp9.Name = "qualifiers";
          tmp9.Type = TType.Map;
          tmp9.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp9, cancellationToken);
          await oprot.WriteMapBeginAsync(new TMap(TType.String, TType.Struct, Qualifiers.Count), cancellationToken);
          foreach (string _iter10 in Qualifiers.Keys)
          {
            await oprot.WriteStringAsync(_iter10, cancellationToken);
            await Qualifiers[_iter10].WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteMapEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object? that)
    {
      if (that is not TTypeQualifiers other) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.qualifiers == other.__isset.qualifiers) && ((!__isset.qualifiers) || (TCollections.Equals(Qualifiers, other.Qualifiers))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Qualifiers != null) && __isset.qualifiers)
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Qualifiers);
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp11 = new StringBuilder("TTypeQualifiers(");
      int tmp12 = 0;
      if((Qualifiers != null) && __isset.qualifiers)
      {
        if(0 < tmp12++) { tmp11.Append(", "); }
        tmp11.Append("Qualifiers: ");
        Qualifiers.ToString(tmp11);
      }
      tmp11.Append(')');
      return tmp11.ToString();
    }
  }

}
